Add UITabBarController, add 5 ViewControllers, add labels in each vc
Nam-Namazov/homeWork pull request #2
Opened 2022-05-13 15:00 UTC by Nam-Namazov

2022-05-13 15:16 UTC, Nam-Namazov commented
Hey, Boss, check my pull request pls @N-ihad

2022-05-14 00:43 UTC, N-ihad requested changes

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Application/SceneDelegate.swift
> +        window?.overrideUserInterfaceStyle = .light
what's that for

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/AboutViewController.swift
> +class AboutViewController: UIViewController {
make class **final** if you don't intend others to inherit from your class

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/AboutViewController.swift
> +    private var label4 = UILabel()
give a meaningful name and make it **let**

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/AboutViewController.swift
> +        label4.textColor = .black
move this to where label4 is defined and initialize and change properties in a closure

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/ContactsViewController.swift
> +class ContactsViewController: UIViewController {
same here as before, make **final** if you don't intend others to inherit from your class

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/ContactsViewController.swift
> +    private var label2 = UILabel()
same as before, change to **let**

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/ContactsViewController.swift
> +        label2.textColor = .black
same

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/HelpViewController.swift
> +class HelpViewController: UIViewController {
same

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/HelpViewController.swift
> +    private var label3 = UILabel()
same

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/HelpViewController.swift
> +        label3.textColor = .black
same

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/HomeViewController.swift
> +class HomeViewController: UIViewController {
same

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/HomeViewController.swift
> +    private var label1 = UILabel()
same

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/HomeViewController.swift
> +        label1.textColor = .black
same

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/MainTabBarController.swift
> +class MainTabBarController: UITabBarController {
same

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/MainTabBarController.swift
> +
remove unnecessary empty space line

2022-05-14 00:43 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/SettingsViewController.swift
> +class SettingsViewController: UIViewController {
same

2022-05-15 22:00 UTC, N-ihad commented on homeWorkApp/homeWorkApp/Controllers/MainTabBarController.swift
> +class MainTabBarController: UITabBarController {
Final here as well

2022-05-15 22:02 UTC, N-ihad approved these changes

2022-05-16 08:25 UTC, merged